version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atsapp
    restart: always
    ports:
      - "7774:80"
      - "884:443"
      - "884:443/udp"
    volumes:
      - ./apps:/var/www/html
      - ./ssl:/etc/ssl/certs
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=atsdb
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - db
    networks:
      - atsLaravel

  db:
    image: mariadb:latest
    container_name: atsdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: atsdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - atsLaravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: atsphpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
    depends_on:
      - db
    networks:
      - atsLaravel

networks:
  atsLaravel:
    driver: bridge
